# Generated by Django 3.1 on 2024-01-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240118_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pincode',
            new_name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
